### ISSUE TITLE
[AQ40] Princess Yauj ran across the room when Lord Kri died

### ISSUE THREAD

**Issue by HS-Disq** [TeamEverlook/Everlook-BugTracker#322]
**Describe the bug**
Upon Lord Kri's death, the remaining bugs should charge the corpse and eat it. While they gain extra abilities, Princess Yauj completely spasmed out and ran everywhere in the room at high speed instead of charging Lord Kri's corpse. Vem stayed where he was instead of charging Lord Kri. Aggro did reset as intended.

**To Reproduce**
1. Go to AQ40
2. Engage Bug Trio.
3. Kill Lord Kri.

**Expected behavior**
The remaining bugs should charge to the corpse of the killed bug and devour it.

**Comment by NiDiCi** [comment]
Hi HS-Disq,

Do you have a recording of this or any more information that could help reproduce this bug. I've tried it 10 times on the ptr without any issues, might have been something with the recent patch perhaps but if so it will be fixed with the server reset. Let us know if you have any additional information you can give otherwise I will close this issue.

**Comment by HS-Disq** [comment]
https://www.twitch.tv/videos/2039570680?t=00h18m35s right here. Vem looks okay, Yauj sprints off to the other side at the speed of light.

**Comment by NiDiCi** [comment]
Hi HS-Disq,

I'm going to close this issue, I've tried to reproduce it again and I'm not able to. Thanks for the video, and if this happens again I'd appreciate another recording of that so that we can search for commonalities between the separate instances.
