### ISSUE TITLE
Chests dont seem to have the correct loot

### ISSUE THREAD

**Issue by fischerderheld** [TeamEverlook/Everlook-BugTracker#358]
**Describe the bug**
I opened a few chests in wetlands now and they seem to have the wrong loot. The items are like from a chest in elywnn forrest. 

**To Reproduce**
Go loot a few chests in wetlands and see for yourself

**Expected behavior**
Check out the possible loot on wowhead. All green items are arround level 17-20 (https://www.wowhead.com/classic/object=2850/solid-chest#contains;mode:normal;150)

**Screenshots**
See what Item i looted for example
(https://discord.com/channels/973529971740008448/1149040979496681542/1260656539551928361)

I hope this helps

**Comment by jensbond420** [comment]
https://classicdb.ch/?object=2850#contains:100+5-16+1

I checked Classicdb and found plenty of low level 5 green items in the loot table out of Solid Chest 2850. I couldnt find Severing Axe in Classicdb, however since there are many other low level items. Its possible that its an incomplete list.

Your link says there is 178 possible items that can drop
Classicdb says there is 750 possible items that can drop

**Comment by jensbond420** [comment]
Closing this issue. Solid Chest are supposed to have level 5 greens.

**Comment by Simp-N** [comment]
Is there any other source that shows these chests should have lvl 5 items? I mean, Classicdb is itself just based on some project similar to vmangos so naturally the drops for this items on Everlook and Classicdb are gonna match up. If Wowhead shows these chests only have have 20+ items, it might be reason to *change* the database (especially since the chests only spawn in +20 areas), rather than just pointing back to the database itself as a source.
